name: build_release

on:
  workflow_dispatch:
  schedule:
      - cron: '0 19 * * *'  # 北京时间 3: 00

jobs:
  build_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name:  配置 Node.js 运行环境
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: 配置 pnpm 包管理器
        uses: pnpm/action-setup@v6

      - name: 安装项目依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm run build

      - name: 生成版本号
        id: version
        run: |
          version=$(node -e "import('@gkd-kit/tools').then((m) => m.stdoutGkdVersion());")
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: 提交构建产物
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git status
          git add .
          git commit -a -m "chore: v${{steps.version.outputs.version}}"
        continue-on-error: true

      - name: 推送代码到远程仓库
        if: ${{ steps.commit.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: 创建 GitHub 发行版
        if: ${{ steps.commit.outcome == 'success' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body_path: ./dist/CHANGELOG.md
